import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/header'
import Navbar from '../components/navbar'
import Feature from '../components/feature-header'
import Footer from '../components/footer'
import FeatureList from '../components/feature-list'
import Content from '../components/content-block'

const Home: NextPage = () => {
  return (
    <div>
      <div >
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon"  ="/favicon.ico" />
          <link  ="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet"></link>
        </Head>
        <div className='-z-10 pb-3 drop-shadow-md bg-gradient-to-r from-cyan-300 to-blue-100'>
          <Navbar />
          <Header />

        </div>
        <Feature />
      </div>
      <div className="pb-3 drop-shadow-md bg-gradient-to-b from-cyan-300 to-blue-100">
        <Content />
        <FeatureList />
      </div>

      <Footer />
    </div >
  )
}

export default Home
